### ISSUE TITLE
Remove login from menu

### ISSUE THREAD

**Issue by wms3** [water42/TractNotes#60]
User should just be redirected to a login page when necessary

**Comment by Schaff** [comment]
User needs to logout. What about an account page instead?

**Comment by water42** [comment]
logout should be an option in settings; eventually we'll refactor control.controller to settings.controller

**Comment by water42** [comment]
thinking about it more, it might be best to confirm this with Dave before rewriting anything

**Comment by water42** [comment]
Update from meeting:

Remove login from menu, add logout option to settings

**Comment by wms3** [comment]
Login has been removed from menu, login/logout placeholder is in Settings
