### ISSUE TITLE
Refactor layer management views based on feedback from meeting

### ISSUE THREAD

**Issue by wms3** [water42/TractNotes#64]

**Comment by water42** [comment]
Menu order: 
Forms
Tracks (manage tracks, move import/edit/export track as modal)
Layers (two buttons: CT ECO (current CT ECO view) and WMS layers (current WMS view, maybe add WMS as modal) manage layers)
Settings (draw tools settings, cache, log out)
Exit button
remove login

Note that this also relates to issue #61
