### ISSUE TITLE
Google Auth features

### ISSUE THREAD

**Issue by water42** [water42/TractNotes#7]
- Log out button
- Display logged in user with picture, name and email in a card

**Comment by Schaff** [comment]
Complete by 4/1/16

**Comment by Schaff** [comment]
For user login info, the id_token does not return name/picture url as it should. Possible solutions are enabling google+ api, making an android api key with package matching project and SHA1 key matching the computer running the app, and making sure the app is signed (debug or private release SHA1 key should work).

Reference: https://github.com/EddyVerbruggen/cordova-plugin-googleplus/issues/123
